package admin.entity;
// Generated 20:03:11, 16 thg 4, 2024 by Hibernate Tools 5.6.15.Final

/**
 * FavouriteProduct generated by hbm2java
 */
public class FavouriteProduct {
	 private int pid;
	    private int uid;
	    private int id;
		public FavouriteProduct(int pid, int uid, int id) {
			super();
			this.pid = pid;
			this.uid = uid;
			this.id = id;
		}
		public FavouriteProduct() {
		}
		public int getPid() {
			return pid;
		}
		public void setPid(int pid) {
			this.pid = pid;
		}
		public int getUid() {
			return uid;
		}
		public void setUid(int uid) {
			this.uid = uid;
		}
		public int getId() {
			return id;
		}
		public void setId(int id) {
			this.id = id;
		}
	    
	    

}
