package admin.entity;
// Generated 20:03:11, 16 thg 4, 2024 by Hibernate Tools 5.6.15.Final

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails  {
	   private int oid;
	    private int quantity;
	    private int pid;
	    private int id;
		public OrderDetails() {
		}
		public OrderDetails(int oid, int quantity, int pid, int id) {
			super();
			this.oid = oid;
			this.quantity = quantity;
			this.pid = pid;
			this.id = id;
		}
		public int getOid() {
			return oid;
		}
		public void setOid(int oid) {
			this.oid = oid;
		}
		public int getQuantity() {
			return quantity;
		}
		public void setQuantity(int quantity) {
			this.quantity = quantity;
		}
		public int getPid() {
			return pid;
		}
		public void setPid(int pid) {
			this.pid = pid;
		}
		public int getId() {
			return id;
		}
		public void setId(int id) {
			this.id = id;
		}
	    
	    

}
