package admin.entity;
// Generated 20:03:11, 16 thg 4, 2024 by Hibernate Tools 5.6.15.Final

/**
 * Size generated by hbm2java
 */
public class Size{
	   private int pid;
	    private int size;
	    private double price;
	    private Double salePrice;
	    private int quantity;
	    private int id;

	public Size() {
	}

	public Size(int pid, int size, double price, Double salePrice, int quantity, int id) {
		super();
		this.pid = pid;
		this.size = size;
		this.price = price;
		this.salePrice = salePrice;
		this.quantity = quantity;
		this.id = id;
	}

	public int getPid() {
		return pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public int getSize() {
		return size;
	}

	public void setSize(int size) {
		this.size = size;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Double getSalePrice() {
		return salePrice;
	}

	public void setSalePrice(Double salePrice) {
		this.salePrice = salePrice;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}


}
