package admin.entity;
// Generated 20:03:11, 16 thg 4, 2024 by Hibernate Tools 5.6.15.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users{
	 private int uid;
	    private String fullName;
	    private String avatarUrl;
	    private String userPhone;
	    private String email;
	    private String password;
	    private Date createDate;
	    private boolean isDelete;
	    private String address;
	    private boolean roleId;
		public Users() {
			// TODO Auto-generated constructor stub
		}
		public Users(int uid, String fullName, String avatarUrl, String userPhone, String email, String password,
				Date createDate, boolean isDelete, String address, boolean roleId) {
			this.uid = uid;
			this.fullName = fullName;
			this.avatarUrl = avatarUrl;
			this.userPhone = userPhone;
			this.email = email;
			this.password = password;
			this.createDate = createDate;
			this.isDelete = isDelete;
			this.address = address;
			this.roleId = roleId;
		}
		public int getUid() {
			return uid;
		}
		public void setUid(int uid) {
			this.uid = uid;
		}
		public String getFullName() {
			return fullName;
		}
		public void setFullName(String fullName) {
			this.fullName = fullName;
		}
		public String getAvatarUrl() {
			return avatarUrl;
		}
		public void setAvatarUrl(String avatarUrl) {
			this.avatarUrl = avatarUrl;
		}
		public String getUserPhone() {
			return userPhone;
		}
		public void setUserPhone(String userPhone) {
			this.userPhone = userPhone;
		}
		public String getEmail() {
			return email;
		}
		public void setEmail(String email) {
			this.email = email;
		}
		public String getPassword() {
			return password;
		}
		public void setPassword(String password) {
			this.password = password;
		}
		public Date getCreateDate() {
			return createDate;
		}
		public void setCreateDate(Date createDate) {
			this.createDate = createDate;
		}
		public boolean isDelete() {
			return isDelete;
		}
		public void setDelete(boolean isDelete) {
			this.isDelete = isDelete;
		}
		public String getAddress() {
			return address;
		}
		public void setAddress(String address) {
			this.address = address;
		}
		public boolean isRoleId() {
			return roleId;
		}
		public void setRoleId(boolean roleId) {
			this.roleId = roleId;
		}
	    
	    

}
