package com.example.mockproject3.admin.entity;
// Generated 20:03:11, 16 thg 4, 2024 by Hibernate Tools 5.6.15.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories implements Serializable {

	private Integer cid;
	private Serializable name;
	private Set productses = new HashSet(0);

	public Categories() {
	}

	public Categories(Serializable name) {
		this.name = name;
	}
	
	public Categories(Integer cid, Serializable name) {
		this.cid = cid;
		this.name = name;
	}

	public Categories(Serializable name, Set productses) {
		this.name = name;
		this.productses = productses;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Set getProductses() {
		return this.productses;
	}

	public void setProductses(Set productses) {
		this.productses = productses;
	}

}
