package com.example.mockproject3.admin.entity;
// Generated 20:03:11, 16 thg 4, 2024 by Hibernate Tools 5.6.15.Final

/**
 * FavouriteProduct generated by hbm2java
 */
public class FavouriteProduct implements java.io.Serializable {

	private Integer id;
	private Products products;
	private Users users;

	public FavouriteProduct() {
	}

	public FavouriteProduct(Products products, Users users) {
		this.products = products;
		this.users = users;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
