package com.example.mockproject3.admin.entity;
// Generated 20:03:11, 16 thg 4, 2024 by Hibernate Tools 5.6.15.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private Integer oid;
	private Users users;
	private Date createDate;
	private int status;
	private Set orderDetailses = new HashSet(0);

	public Orders() {
	}

	public Orders(Users users, Date createDate, int status) {
		this.users = users;
		this.createDate = createDate;
		this.status = status;
	}

	public Orders(Users users, Date createDate, int status, Set orderDetailses) {
		this.users = users;
		this.createDate = createDate;
		this.status = status;
		this.orderDetailses = orderDetailses;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Set getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
