package com.example.mockproject3.admin.entity;
// Generated 20:03:11, 16 thg 4, 2024 by Hibernate Tools 5.6.15.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements Serializable {

	private Integer pid;
	private Categories categories;
	private Suppliers suppliers;
	private Serializable productName;
	private Serializable image;
	private String description;
	private Boolean status;
	private Set orderDetailses = new HashSet(0);
	private Set sizes = new HashSet(0);
	private Set favouriteProducts = new HashSet(0);
	private Set rates = new HashSet(0);

	public Products() {
	}

	public Products(Categories categories, Suppliers suppliers, Serializable productName, Serializable image) {
		this.categories = categories;
		this.suppliers = suppliers;
		this.productName = productName;
		this.image = image;
	}

	public Products(Categories categories, Suppliers suppliers, Serializable productName, Serializable image,
			String description, Boolean status, Set orderDetailses, Set sizes, Set favouriteProducts, Set rates) {
		this.categories = categories;
		this.suppliers = suppliers;
		this.productName = productName;
		this.image = image;
		this.description = description;
		this.status = status;
		this.orderDetailses = orderDetailses;
		this.sizes = sizes;
		this.favouriteProducts = favouriteProducts;
		this.rates = rates;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	public Suppliers getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Suppliers suppliers) {
		this.suppliers = suppliers;
	}

	public Serializable getProductName() {
		return this.productName;
	}

	public void setProductName(Serializable productName) {
		this.productName = productName;
	}

	public Serializable getImage() {
		return this.image;
	}

	public void setImage(Serializable image) {
		this.image = image;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Set getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

	public Set getSizes() {
		return this.sizes;
	}

	public void setSizes(Set sizes) {
		this.sizes = sizes;
	}

	public Set getFavouriteProducts() {
		return this.favouriteProducts;
	}

	public void setFavouriteProducts(Set favouriteProducts) {
		this.favouriteProducts = favouriteProducts;
	}

	public Set getRates() {
		return this.rates;
	}

	public void setRates(Set rates) {
		this.rates = rates;
	}

}
