package com.example.mockproject3.admin.entity;
// Generated 20:03:11, 16 thg 4, 2024 by Hibernate Tools 5.6.15.Final

/**
 * Size generated by hbm2java
 */
public class Size implements java.io.Serializable {

	private Integer id;
	private Products products;
	private int size;
	private double price;
	private Double salePrice;
	private int quantity;

	public Size() {
	}

	public Size(Products products, int size, double price, int quantity) {
		this.products = products;
		this.size = size;
		this.price = price;
		this.quantity = quantity;
	}

	public Size(Products products, int size, double price, Double salePrice, int quantity) {
		this.products = products;
		this.size = size;
		this.price = price;
		this.salePrice = salePrice;
		this.quantity = quantity;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public int getSize() {
		return this.size;
	}

	public void setSize(int size) {
		this.size = size;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Double getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(Double salePrice) {
		this.salePrice = salePrice;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
