package com.example.mockproject3.admin.entity;
// Generated 20:03:11, 16 thg 4, 2024 by Hibernate Tools 5.6.15.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements Serializable {

	private Integer uid;
	private Serializable fullName;
	private Serializable avatarUrl;
	private String userPhone;
	private Serializable email;
	private String password;
	private Date createDate;
	private Boolean isDelete;
	private Serializable address;
	private Boolean roleId;
	private Set favouriteProducts = new HashSet(0);
	private Set orderses = new HashSet(0);
	private Set rates = new HashSet(0);

	public Users() {
	}

	public Users(Serializable fullName, Serializable email, String password) {
		this.fullName = fullName;
		this.email = email;
		this.password = password;
	}

	public Users(Serializable fullName, Serializable avatarUrl, String userPhone, Serializable email, String password,
			Date createDate, Boolean isDelete, Serializable address, Boolean roleId, Set favouriteProducts,
			Set orderses, Set rates) {
		this.fullName = fullName;
		this.avatarUrl = avatarUrl;
		this.userPhone = userPhone;
		this.email = email;
		this.password = password;
		this.createDate = createDate;
		this.isDelete = isDelete;
		this.address = address;
		this.roleId = roleId;
		this.favouriteProducts = favouriteProducts;
		this.orderses = orderses;
		this.rates = rates;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Serializable getFullName() {
		return this.fullName;
	}

	public void setFullName(Serializable fullName) {
		this.fullName = fullName;
	}

	public Serializable getAvatarUrl() {
		return this.avatarUrl;
	}

	public void setAvatarUrl(Serializable avatarUrl) {
		this.avatarUrl = avatarUrl;
	}

	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Boolean getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	public Boolean getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Boolean roleId) {
		this.roleId = roleId;
	}

	public Set getFavouriteProducts() {
		return this.favouriteProducts;
	}

	public void setFavouriteProducts(Set favouriteProducts) {
		this.favouriteProducts = favouriteProducts;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

	public Set getRates() {
		return this.rates;
	}

	public void setRates(Set rates) {
		this.rates = rates;
	}

}
